name: Build AmneziaWG for AXT1800 Slate

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:

permissions:
  contents: write

env:
  OWR_BRANCH: openwrt-23.05
  GL_VERSION: '4.8.0'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1) Checkout your MT-3000 fork (contains config_4.8.0.buildinfo)
      - name: Checkout MT-3000 repo
        uses: actions/checkout@v4

      # 2) Clone OpenWrt 23.05 snapshot
      - name: Clone OpenWrt snapshot
        run: |
          git clone --depth 1 \
            --branch "${OWR_BRANCH}" \
            https://github.com/openwrt/openwrt.git openwrt-src

      # 3) Copy in your complete .config
      - name: Apply GL.iNet buildinfo (.config)
        run: |
          cp config_${{ env.GL_VERSION }}.buildinfo openwrt-src/.config

      # 4) Bootstrap the OpenWrt C toolchain (must run before compiling any packages)
      - name: Bootstrap OpenWrt toolchain
        run: |
          cd openwrt-src
          make defconfig
          make -j"$(nproc)" toolchain/install

      # 5) Overlay the three AmneziaWG packages from your repo root
      - name: Overlay AmneziaWG packages
        run: |
          PKGS=$(find . -maxdepth 1 -type d -name 'amneziawg-*' -o -name 'kmod-amneziawg')
          echo "Found packages: $PKGS"
          cp -r $PKGS openwrt-src/package/

      # 6) Prepare feeds
      - name: Prepare feeds
        run: |
          cd openwrt-src
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      # 7) Build only the AmneziaWG packages
      - name: Build AmneziaWG packages
        run: |
          cd openwrt-src
          make package/amneziawg-tools/compile V=s -j"$(nproc)"
          make package/luci-proto-amneziawg/compile V=s -j"$(nproc)"
          make package/kmod-amneziawg/compile V=s -j"$(nproc)"

      # 8) Collect the resulting .ipk files
      - name: Collect artifacts
        run: |
          cd openwrt-src
          mkdir -p awg
          cp bin/packages/aarch64_cortex-a53/base/amneziawg-tools_*.ipk awg/
          cp bin/packages/aarch64_cortex-a53/base/luci-proto-amneziawg_*.ipk awg/
          cp bin/targets/ipq806x/generic/packages/kmod-amneziawg_*.ipk awg/

      # 9) Publish a GitHub Release with those IPKs
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "AmneziaWG v${{ env.GL_VERSION }} (AXT1800)"
          tag_name: "${{ github.ref_name }}"
          files: openwrt-src/awg/*.ipk
```0
