name: Build AmneziaWG for AXT1800 Slate

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:

permissions:
  contents: write

env:
  OWR_BRANCH: openwrt-23.05
  GL_VERSION: '4.8.0'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1) Checkout *your* fork (with config_4.8.0.buildinfo + your three amneziawg-* dirs)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Grab OpenWrt 23.05 snapshot
      - name: Clone OpenWrt snapshot
        run: |
          git clone --depth 1 \
            --branch "${OWR_BRANCH}" \
            https://github.com/openwrt/openwrt.git openwrt-src

      # 3) Drop in your full .config (the 533-line buildinfo you made)
      - name: Apply GL.iNet buildinfo as .config
        run: |
          cp config_${{ env.GL_VERSION }}.buildinfo openwrt-src/.config

      # 4) Generate the default config (so that target/linux headers & .config get populated)
      - name: Set default config
        run: |
          cd openwrt-src
          make defconfig

      # 5) Overlay your three AmneziaWG packages
      - name: Overlay AmneziaWG packages
        run: |
          cd openwrt-src
          PKGS=$(find .. -maxdepth 1 -type d -name 'amneziawg-*' | sed 's#\.\./##')
          echo "Copying overlay packages: $PKGS"
          cp -r $PKGS package/

      # 6) Prepare all feeds
      - name: Prepare feeds
        run: |
          cd openwrt-src
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      # 7) Compile only your three packages (they will auto-pull in toolchain & kernel headers)
      - name: Build AmneziaWG packages
        run: |
          cd openwrt-src
          make package/amneziawg-tools/{clean,compile} V=s -j"$(nproc)"
          make package/luci-proto-amneziawg/{clean,compile} V=s -j"$(nproc)"
          make package/kmod-amneziawg/{clean,compile} V=s -j"$(nproc)"

      # 8) Gather the .ipk artifacts
      - name: Collect artifacts
        run: |
          cd openwrt-src
          mkdir -p awg
          cp bin/packages/*/*/amneziawg-tools_*.ipk awg/
          cp bin/packages/*/*/luci-proto-amneziawg_*.ipk awg/
          cp bin/packages/*/*/kmod-amneziawg_*.ipk awg/

      # 9) Create a GitHub Release with your three .ipk files
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "AmneziaWG v${{ env.GL_VERSION }} (AXT1800)"
          tag_name: "${{ github.ref_name }}"
          files: openwrt-src/awg/*.ipk
