name: Build AmneziaWG for AXT1800 Slate

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:

permissions:
  contents: write

env:
  OWR_BRANCH: openwrt-23.05
  GL_VERSION: '4.8.0'

jobs:
  smoke:
    name: Smoke-test overlay
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4

      - name: Clone OpenWrt 23.05 branch
        run: |
          git clone --depth 1 \
            --branch "${OWR_BRANCH}" \
            https://github.com/openwrt/openwrt.git openwrt-src

      - name: Copy in GL.iNet .config
        run: |
          cp config_${{ env.GL_VERSION }}.buildinfo openwrt-src/.config

      - name: Overlay AmneziaWG packages
        run: |
          PKGS=$(find . -maxdepth 1 -type d -name '*amneziawg*' | sed 's#^\./##')
          echo "Found packages: $PKGS"
          cp -r $PKGS openwrt-src/package/

      - name: Defconfig (quick)
        run: |
          cd openwrt-src
          make defconfig

      - name: Verify AmneziaWG targets exist
        run: |
          cd openwrt-src
          for P in amneziawg-tools luci-proto-amneziawg kmod-amneziawg; do
            grep -q "package/${P}/compile" include/toplevel.mk \
              && echo "${P} is registered" \
              || (echo "${P} missing from toplevel.mk"; exit 1)
          done

  build:
    name: Full build
    needs: smoke
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4

      - name: Clone OpenWrt 23.05 branch
        run: |
          git clone --depth 1 \
            --branch "${OWR_BRANCH}" \
            https://github.com/openwrt/openwrt.git openwrt-src

      - name: Copy in GL.iNet .config
        run: |
          cp config_${{ env.GL_VERSION }}.buildinfo openwrt-src/.config

      - name: Bootstrap toolchain
        run: |
          cd openwrt-src
          make defconfig
          make -j"$(nproc)" toolchain/install

      - name: Overlay AmneziaWG packages
        run: |
          PKGS=$(find . -maxdepth 1 -type d -name '*amneziawg*' | sed 's#^\./##')
          cp -r $PKGS openwrt-src/package/

      - name: Prepare feeds
        run: |
          cd openwrt-src
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build only AmneziaWG packages
        run: |
          cd openwrt-src
          make -j"$(nproc)" package/amneziawg-tools/compile V=s
          make -j"$(nproc)" package/luci-proto-amneziawg/compile V=s
          make -j"$(nproc)" package/kmod-amneziawg/compile V=s

      - name: Collect artifacts
        run: |
          cd openwrt-src
          mkdir -p awg
          cp bin/packages/*/base/amneziawg-tools_*.ipk    awg/
          cp bin/packages/*/base/luci-proto-amneziawg_*.ipk awg/
          cp bin/targets/*/*/packages/kmod-amneziawg_*.ipk awg/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name:     "AmneziaWG v${{ env.GL_VERSION }} (AXT1800)"
          files:    openwrt-src/awg/*.ipk
