name: Build AmneziaWG for AXT1800 Slate

# Trigger on any new tag (for releases) or PRs against main
on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

env:
  OWR_BRANCH: openwrt-23.05
  GL_VERSION: 4.8.0

jobs:
  ###########################################################################
  # 1) Quick smoke-test: ensure our overlay packages get into .config        #
  ###########################################################################
  smoke-test-overlay:
    name: Smoke-test overlay
    runs-on: ubuntu-latest
    steps:
      - name: Checkout AmneziaWG overlay
        uses: actions/checkout@v4
        with:
          path: amneziawg-overlay

      - name: Clone OpenWrt snapshot
        run: |
          git clone --depth 1 --branch $OWR_BRANCH https://github.com/openwrt/openwrt openwrt-src

      - name: Copy GL.iNet buildinfo (.config)
        run: |
          cp config_${{ env.GL_VERSION }}.buildinfo openwrt-src/.config

      - name: Overlay AmneziaWG packages
        run: |
          cd openwrt-src
          cp -R ../amneziawg-overlay/amneziawg-tools     package/
          cp -R ../amneziawg-overlay/luci-proto-amneziawg package/
          cp -R ../amneziawg-overlay/kmod-amneziawg      package/

      - name: Quick defconfig for smoke
        run: |
          cd openwrt-src
          scripts/config/defconfig \
            --enable amneziawg_tools \
            --enable luci_proto_amneziawg \
            --enable kmod_amneziawg

      - name: Verify .config contains our packages
        run: |
          cd openwrt-src
          grep -q 'CONFIG_PACKAGE_amneziawg_tools=y'     .config
          grep -q 'CONFIG_PACKAGE_luci_proto_amneziawg=y' .config
          grep -q 'CONFIG_PACKAGE_kmod_amneziawg=y'      .config

  ###########################################################################
  # 2) Full build & release: only runs if smoke-test-overlay succeeded      #
  ###########################################################################
  full-build-and-release:
    name: Full build & release
    needs: smoke-test-overlay
    runs-on: ubuntu-latest
    steps:
      - name: Checkout AmneziaWG overlay
        uses: actions/checkout@v4
        with:
          path: amneziawg-overlay

      - name: Clone OpenWrt snapshot
        run: |
          git clone --depth 1 --branch $OWR_BRANCH https://github.com/openwrt/openwrt openwrt-src

      - name: Apply GL.iNet buildinfo (.config)
        run: |
          cp config_${{ env.GL_VERSION }}.buildinfo openwrt-src/.config

      - name: Bootstrap OpenWrt toolchain
        run: |
          cd openwrt-src
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          make -j$(nproc) toolchain/install

      - name: Overlay AmneziaWG packages
        run: |
          cd openwrt-src
          cp -R ../amneziawg-overlay/amneziawg-tools     package/
          cp -R ../amneziawg-overlay/luci-proto-amneziawg package/
          cp -R ../amneziawg-overlay/kmod-amneziawg      package/

      - name: Prepare feeds
        run: |
          cd openwrt-src
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Enable AmneziaWG packages in .config
        run: |
          cd openwrt-src
          cat << 'EOF' >> .config
          CONFIG_PACKAGE_amneziawg_tools=y
          CONFIG_PACKAGE_luci_proto_amneziawg=y
          CONFIG_PACKAGE_kmod_amneziawg=y
          EOF
          make defconfig

      - name: Build only AmneziaWG packages
        run: |
          cd openwrt-src
          make -j$(nproc) \
            package/amneziawg-tools/compile \
            package/luci-proto-amneziawg/compile \
            package/kmod-amneziawg/compile

      - name: Collect every AmneziaWG .ipk
        run: |
          cd openwrt-src
          mkdir -p awg
          find bin -type f -name 'amneziawg-tools_*.ipk'     -exec cp {} awg/ \;
          find bin -type f -name 'luci-proto-amneziawg_*.ipk' -exec cp {} awg/ \;
          find bin -type f -name 'kmod-amneziawg_*.ipk'      -exec cp {} awg/ \;

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name:      "AmneziaWG v${{ env.GL_VERSION }} ($OWR_BRANCH)"
          files:     openwrt-src/awg/*.ipk
