name: Build AmneziaWG for AXT1800 Slate

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:

permissions:
  contents: write

env:
  OWR_BRANCH: openwrt-23.05
  GL_VERSION: '4.8.0'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1) Checkout *your* fork (with config_4.8.0.buildinfo + amneziawg-* dirs)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Clone official OpenWrt 23.05 into openwrt-src/
      - name: Clone OpenWrt snapshot
        run: |
          git clone --depth 1 \
            --branch "${OWR_BRANCH}" \
            https://github.com/openwrt/openwrt.git openwrt-src

      # 3) Inject your full .config
      - name: Apply GL.iNet buildinfo (.config)
        run: |
          cp config_${{ env.GL_VERSION }}.buildinfo openwrt-src/.config

      # 4) Bootstrap the toolchain
      - name: Bootstrap OpenWrt toolchain
        run: |
          cd openwrt-src
          make defconfig
          make -j"$(nproc)" toolchain/install

      # 5) Overlay your three AmneziaWG packages
      - name: Overlay AmneziaWG packages
        run: |
          PKGS=$(find . -maxdepth 1 -type d -name '*amneziawg*' | sed 's#^\./##')
          echo "Copying packages: $PKGS"
          cp -r $PKGS openwrt-src/package/

      # 6) Update & install feeds
      - name: Prepare feeds
        run: |
          cd openwrt-src
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      # 7) Compile just your three packages
      - name: Build AmneziaWG packages
        run: |
          cd openwrt-src
          make package/amneziawg-tools/compile V=s -j"$(nproc)"
          make package/luci-proto-amneziawg/compile V=s -j"$(nproc)"
          make package/kmod-amneziawg/compile V=s -j"$(nproc)"

      # 8) Gather the resulting .ipk files from the correct IPQ806x paths
      - name: Collect artifacts
        run: |
          cd openwrt-src
          mkdir -p awg
          # tools + luci (arch-independent feed under arm_cortex-a15+neon-vfpv4)
          cp bin/packages/arm_cortex-a15+neon-vfpv4_musl_eabi/base/amneziawg-tools_*.ipk awg/
          cp bin/packages/arm_cortex-a15+neon-vfpv4_musl_eabi/base/luci-proto-amneziawg_*.ipk awg/
          # kernel module (IPQ806x target)
          cp bin/targets/ipq806x/generic/packages/kmod-amneziawg_*.ipk awg/

      # 9) Publish a GitHub Release with your IPKs
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "AmneziaWG v${{ env.GL_VERSION }} (AXT1800)"
          tag_name: "${{ github.ref_name }}"
          files: openwrt-src/awg/*.ipk
