name: Build AmneziaWG for ATX1800 Slate

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:

permissions:
  contents: write

env:
  OWR_BRANCH: openwrt-23.05
  GL_VERSION: '4.8.0'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1) Checkout your fork (contains config_4.8.0.buildinfo and the three amneziawg-* dirs)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Grab the official OpenWrt 23.05 snapshot
      - name: Clone OpenWrt snapshot
        run: |
          git clone --depth 1 \
            --branch "${OWR_BRANCH}" \
            https://github.com/openwrt/openwrt.git openwrt-src

      # 3) Inject your full .config (the 4.8.0 buildinfo you generated)
      - name: Apply GL.iNet buildinfo (.config)
        run: |
          cp config_${{ env.GL_VERSION }}.buildinfo openwrt-src/.config

      # 4) Bootstrap the toolchain (needed before any package compile)
      - name: Bootstrap OpenWrt toolchain
        run: |
          cd openwrt-src
          make defconfig
          make -j "$(nproc)" toolchain/install

      # 5) Overlay the three AmneziaWG packages from your repo root
      - name: Overlay AmneziaWG packages
        run: |
          PKGS=$(find . -maxdepth 1 -type d -name '*amneziawg*' -printf '%f ')
          echo "Copying packages: $PKGS"
          cp -r $PKGS openwrt-src/package/

      # 6) Pull in all feeds
      - name: Prepare feeds
        run: |
          cd openwrt-src
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      # 7) Compile only your three packages
      - name: Build AmneziaWG packages
        run: |
          cd openwrt-src
          make package/amneziawg-tools/compile V=s -j"$(nproc)"
          make package/luci-proto-amneziawg/compile V=s -j"$(nproc)"
          make package/kmod-amneziawg/compile V=s -j"$(nproc)"

      # 8) Gather the resulting .ipk files
      - name: Collect artifacts
        run: |
          cd openwrt-src
          mkdir -p awg
          cp bin/packages/aarch64_cortex-a53/base/amneziawg-tools_*.ipk    awg/
          cp bin/packages/aarch64_cortex-a53/base/luci-proto-amneziawg_*.ipk awg/
          cp bin/targets/ipq806x/generic/packages/kmod-amneziawg_*.ipk      awg/

      # 9) Publish a GitHub Release with them
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name:    "AmneziaWG v${{ env.GL_VERSION }} (ATX1800)"
          tag_name: "${{ github.ref_name }}"
          files:   openwrt-src/awg/*.ipk
