name: Build AmneziaWG for AXT1800 Slate

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:

permissions:
  contents: write

env:
  OWR_BRANCH: openwrt-23.05
  GL_VERSION: '4.8.0'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1) Checkout *your* fork (with config_4.8.0.buildinfo + amneziawg-tools, kmod-amneziawg, luci-proto-amneziawg in the root)
      - name: Checkout overlay repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 2) Clone the official OpenWrt 23.05 snapshot
      - name: Clone OpenWrt snapshot
        run: |
          git clone --depth 1 \
            --branch "${{ env.OWR_BRANCH }}" \
            https://github.com/openwrt/openwrt.git openwrt-src

      # 3) Copy in your full .config (4.8.0 buildinfo)
      - name: Apply GL.iNet buildinfo (.config)
        run: |
          cp config_${{ env.GL_VERSION }}.buildinfo openwrt-src/.config

      # 4) Regenerate defaults
      - name: Initialize build
        run: |
          cd openwrt-src
          make defconfig

      # 5) Overlay exactly your three packages
      - name: Overlay AmneziaWG packages
        run: |
          cd openwrt-src
          echo "Copying amneziawg-tools, luci-proto-amneziawg, kmod-amneziawg into package/"
          cp -r ../amneziawg-tools  package/
          cp -r ../luci-proto-amneziawg package/
          cp -r ../kmod-amneziawg        package/

      # 6) Update & install feeds
      - name: Update & install feeds
        run: |
          cd openwrt-src
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      # 7) Enable your packages (keeps .config in sync)
      - name: Enable AmneziaWG packages
        run: |
          cd openwrt-src
          scripts/config --enable PACKAGE_amneziawg-tools
          scripts/config --enable PACKAGE_luci-proto-amneziawg
          scripts/config --enable PACKAGE_kmod-amneziawg
          make defconfig

      # 8) Compile just your three packages
      - name: Build AmneziaWG packages
        run: |
          cd openwrt-src
          make package/amneziawg-tools/compile V=s -j"$(nproc)"
          make package/luci-proto-amneziawg/compile V=s -j"$(nproc)"
          make package/kmod-amneziawg/compile V=s -j"$(nproc)"

      # 9) Gather all three .ipk files (tools, luci, kmod)
      - name: Collect artifacts
        run: |
          cd openwrt-src
          mkdir -p awg
          cp bin/packages/*/base/amneziawg-tools_*.ipk awg/ 2>/dev/null || echo "no tools ipk"
          cp bin/packages/*/base/luci-proto-amneziawg_*.ipk awg/ 2>/dev/null || echo "no luci ipk"
          cp bin/targets/*/*/packages/kmod-amneziawg_*.ipk awg/ 2>/dev/null || echo "no kmod ipk"

      # 10) Publish those three IPKs on a GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "AmneziaWG v${{ env.GL_VERSION }} (AXT1800)"
          tag_name: "${{ github.ref_name }}"
          files: openwrt-src/awg/*.ipk
