name: Build AmneziaWG for AXT1800 Slate

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:

permissions:
  contents: write

env:
  OWR_BRANCH: openwrt-23.05
  GL_VERSION: '4.8.0'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4

      - name: Clone OpenWrt 23.05 snapshot
        run: |
          git clone --depth 1 \
            --branch "${OWR_BRANCH}" \
            https://github.com/openwrt/openwrt.git openwrt-src

      - name: Apply GL.iNet .config
        run: |
          cp config_${{ env.GL_VERSION }}.buildinfo openwrt-src/.config

      - name: Bootstrap OpenWrt toolchain
        run: |
          cd openwrt-src
          make defconfig
          make -j"$(nproc)" toolchain/install

      - name: Compile Linux kernel headers only
        run: |
          cd openwrt-src
          # build just the kernel headers/staging area
          make -j"$(nproc)" target/linux/compile

      - name: Overlay AmneziaWG packages
        run: |
          PKGS=$(find . -maxdepth 1 -type d -name '*amneziawg*' | sed 's#^\./##')
          echo "Overlaying: $PKGS"
          cp -r $PKGS openwrt-src/package/

      - name: Prepare feeds
        run: |
          cd openwrt-src
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build only AmneziaWG packages
        run: |
          cd openwrt-src
          make -j"$(nproc)" package/amneziawg-tools/compile V=s
          make -j"$(nproc)" package/luci-proto-amneziawg/compile V=s
          make -j"$(nproc)" package/kmod-amneziawg/compile V=s

      - name: Collect artifacts
        run: |
          cd openwrt-src
          mkdir -p awg
          cp bin/packages/*/base/amneziawg-tools_*.ipk    awg/
          cp bin/packages/*/base/luci-proto-amneziawg_*.ipk awg/
          cp bin/targets/*/*/packages/kmod-amneziawg_*.ipk awg/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name:     "AmneziaWG v${{ env.GL_VERSION }} (AXT1800)"
          files:    openwrt-src/awg/*.ipk
