name: Build AmneziaWG for AXT1800 Slate

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:

permissions:
  contents: write

env:
  OWR_BRANCH: openwrt-23.05
  GL_VERSION: '4.8.0'

jobs:
  smoke-test:
    name: 🧪 Smoke-test overlay
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4

      - name: Clone OpenWrt snapshot
        run: |
          git clone --depth 1 \
            --branch "${OWR_BRANCH}" \
            https://github.com/openwrt/openwrt.git openwrt-src

      - name: Copy in GL.iNet buildinfo (.config)
        run: |
          cp config_${{ env.GL_VERSION }}.buildinfo openwrt-src/.config

      - name: Overlay AmneziaWG packages
        run: |
          cd openwrt-src
          PKGS=$(find .. -maxdepth 1 -type d -name '*amneziawg*' | sed 's#^\.\./##')
          echo "Copying packages: $PKGS"
          cp -r $PKGS package/

      - name: Quick defconfig for smoke
        run: |
          cd openwrt-src
          make defconfig

      - name: Verify .config contains our packages
        run: |
          cd openwrt-src
          grep -q 'CONFIG_PACKAGE_amneziawg-tools=y' .config
          grep -q 'CONFIG_PACKAGE_luci-proto-amneziawg=y' .config
          grep -q 'CONFIG_PACKAGE_kmod-amneziawg=y' .config

  build:
    name: 🔨 Full build & release
    needs: smoke-test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4

      - name: Clone OpenWrt snapshot
        run: |
          git clone --depth 1 \
            --branch "${OWR_BRANCH}" \
            https://github.com/openwrt/openwrt.git openwrt-src

      - name: Copy in GL.iNet buildinfo (.config)
        run: |
          cp config_${{ env.GL_VERSION }}.buildinfo openwrt-src/.config

      - name: Bootstrap OpenWrt toolchain
        run: |
          cd openwrt-src
          make defconfig
          make -j"$(nproc)" toolchain/install

      - name: Overlay AmneziaWG packages
        run: |
          cd openwrt-src
          PKGS=$(find .. -maxdepth 1 -type d -name '*amneziawg*' | sed 's#^\.\./##')
          cp -r $PKGS package/

      - name: Prepare feeds
        run: |
          cd openwrt-src
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build AmneziaWG packages
        run: |
          cd openwrt-src
          make -j"$(nproc)" \
            package/amneziawg-tools/compile V=s \
            package/luci-proto-amneziawg/compile V=s \
            package/kmod-amneziawg/compile V=s

      - name: Collect artifacts
        run: |
          cd openwrt-src
          mkdir -p awg
          find bin -type f -name 'amneziawg-*.ipk' -exec cp {} awg/ \;

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ github.ref_name }}"
          name: "AmneziaWG v${{ env.GL_VERSION }} (AXT1800)"
          files: openwrt-src/awg/*.ipk
