name: Build AmneziaWG for AXT1800 Slate (SDK)

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:

permissions:
  contents: write

env:
  SDK_REPO: https://github.com/gl-inet/sdk.git
  SDK_TARGET: ipq807x-2102        # the AXT1800 target in GL.iNet’s SDK
  GL_VERSION: '4.8.0'             # matches your config_4.8.0.buildinfo

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1) Your fork (with buildinfo + amneziawg-*/ dirs in repo root)
      - name: Checkout overlay
        uses: actions/checkout@v4

      # 2) Clone the GL.iNet SDK
      - name: Clone GL.iNet SDK repo
        run: |
          git clone --depth 1 "${{ env.SDK_REPO }}" glinet-sdk

      # 3) Download the pre-built AXT1800 SDK
      - name: Download AXT1800 SDK
        run: |
          cd glinet-sdk
          chmod +x download.sh
          ./download.sh "${{ env.SDK_TARGET }}"

      # 4) Locate the unpacked SDK directory
      - name: Find SDK path
        id: sdkpath
        run: |
          # this will return e.g. glinet-sdk/sdk/2102/ipq807x
          sdk=$(find glinet-sdk -type d -name "${{ env.SDK_TARGET }}" | head -n1)
          echo "sdk_path=$sdk" >> $GITHUB_OUTPUT

      # 5) Overlay your three packages into that SDK
      - name: Overlay AmneziaWG packages
        run: |
          cd "${{ steps.sdkpath.outputs.sdk_path }}"
          cp -r $GITHUB_WORKSPACE/amneziawg-tools      .
          cp -r $GITHUB_WORKSPACE/luci-proto-amneziawg .
          cp -r $GITHUB_WORKSPACE/kmod-amneziawg       .

      # 6) Copy in your full .config (the 4.8.0 buildinfo)
      - name: Apply GL.iNet buildinfo (.config)
        run: |
          cd "${{ steps.sdkpath.outputs.sdk_path }}"
          cp $GITHUB_WORKSPACE/config_${{ env.GL_VERSION }}.buildinfo .config

      # 7) Build just your three packages via builder.sh
      - name: Build AmneziaWG packages
        run: |
          cd glinet-sdk
          chmod +x builder.sh
          ./builder.sh amneziawg-tools luci-proto-amneziawg kmod-amneziawg

      # 8) Collect the resulting .ipks
      - name: Collect artifacts
        run: |
          SDK_PATH="${{ steps.sdkpath.outputs.sdk_path }}"
          IPK_DIR="$SDK_PATH/bin/openwrt-sdk"
          mkdir awg
          cp $IPK_DIR/*/amneziawg-tools_*.ipk      awg/
          cp $IPK_DIR/*/luci-proto-amneziawg_*.ipk awg/
          cp $IPK_DIR/*/kmod-amneziawg_*.ipk       awg/

      # 9) Publish them in a GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name:    "AmneziaWG v${{ env.GL_VERSION }} (AXT1800)"
          files:   awg/*.ipk
