name: Build AmneziaWG for AXT1800 Slate

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

env:
  OWR_BRANCH: openwrt-23.05
  GL_VERSION: '4.8.0'

jobs:
  smoke-test:
    name: Smoke-test overlay
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4

      - name: Clone OpenWrt ${OWR_BRANCH} snapshot
        run: |
          git clone --depth 1 \
            --branch "${OWR_BRANCH}" \
            https://github.com/openwrt/openwrt.git openwrt-src

      - name: Overlay AmneziaWG packages
        run: |
          cd openwrt-src
          echo "Root contains:" && ls -1 ../*amneziawg* || true
          echo "Copying overlay into openwrt-src/package…" 
          for pkg in ../*amneziawg*; do
            [ -d "$pkg" ] && cp -R "$pkg" package/ && echo "  → $pkg"
          done

      - name: Verify overlay landed
        run: |
          cd openwrt-src/package
          ls -1 | grep -E '^amneziawg-tools$|^luci-proto-amneziawg$|^kmod-amneziawg$'

  build:
    name: Full build & Release
    needs: smoke-test
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4

      - name: Clone OpenWrt ${OWR_BRANCH} snapshot
        run: |
          git clone --depth 1 \
            --branch "${OWR_BRANCH}" \
            https://github.com/openwrt/openwrt.git openwrt-src

      - name: Apply GL.iNet buildinfo (.config)
        run: |
          cp config_${GL_VERSION}.buildinfo openwrt-src/.config

      - name: Bootstrap OpenWrt toolchain
        run: |
          cd openwrt-src
          make defconfig
          make -j"$(nproc)" toolchain/install

      - name: Overlay AmneziaWG packages
        run: |
          cd openwrt-src
          for pkg in ../*amneziawg*; do
            [ -d "$pkg" ] && cp -R "$pkg" package/
          done

      - name: Prepare feeds
        run: |
          cd openwrt-src
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build only AmneziaWG packages
        run: |
          cd openwrt-src
          make -j"$(nproc)" V=s \
            package/amneziawg-tools/compile \
            package/luci-proto-amneziawg/compile \
            package/kmod-amneziawg/compile

      - name: Collect every AmneziaWG .ipk
        run: |
          cd openwrt-src
          mkdir -p awg
          find bin/packages -type f \
            \( -name 'amneziawg-tools_*.ipk' \
            -o -name 'luci-proto-amneziawg_*.ipk' \
            -o -name 'kmod-amneziawg_*.ipk' \) \
          -exec cp {} awg/ \;

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "AmneziaWG v${{ env.GL_VERSION }} (AXT1800)"
          tag_name: "${{ github.ref_name }}"
          files: openwrt-src/awg/*.ipk
