name: Build AmneziaWG for AXT1800 Slate

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:

permissions:
  contents: write

env:
  OWR_BRANCH: openwrt-23.05
  GL_VERSION: '4.8.0'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1) Checkout *your* fork (with config_4.8.0.buildinfo + the three amneziawg-* dirs)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Clone the official OpenWrt 23.05 snapshot into openwrt-src/
      - name: Clone OpenWrt snapshot
        run: |
          git clone --depth 1 \
            --branch "${OWR_BRANCH}" \
            https://github.com/openwrt/openwrt.git openwrt-src

      # 3) Copy in your .config (the 4.8.0 buildinfo)
      - name: Apply GL.iNet buildinfo (.config)
        run: |
          cp config_${{ env.GL_VERSION }}.buildinfo openwrt-src/.config

      # 4) Bootstrap the toolchain (brings in kernel headers, etc.)
      - name: Bootstrap OpenWrt toolchain
        run: |
          cd openwrt-src
          make defconfig
          make -j"$(nproc)" toolchain/install

      # 5) Overlay your three AmneziaWG packages into the OpenWrt tree
      - name: Overlay AmneziaWG packages
        run: |
          echo "Copying overlay packages…"
          for pkg in amneziawg-tools luci-proto-amneziawg kmod-amneziawg; do
            cp -r "${{ github.workspace }}/$pkg" openwrt-src/package/
          done

      # 6) Prepare feeds inside the OpenWrt tree
      - name: Prepare feeds
        run: |
          cd openwrt-src
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      # 7) Build only your three packages
      - name: Build AmneziaWG packages
        run: |
          cd openwrt-src
          make package/amneziawg-tools/compile V=s -j"$(nproc)"
          make package/luci-proto-amneziawg/compile V=s -j"$(nproc)"
          make package/kmod-amneziawg/compile V=s -j"$(nproc)"

      # 8) Collect the generated .ipk files
      - name: Collect artifacts
        run: |
          cd openwrt-src
          mkdir -p awg
          cp bin/packages/aarch64_cortex-a53/base/amneziawg-tools_*.ipk awg/
          cp bin/packages/aarch64_cortex-a53/base/luci-proto-amneziawg_*.ipk awg/
          cp bin/targets/ipq806x/generic/packages/kmod-amneziawg_*.ipk awg/

      # 9) Push them up in a GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "AmneziaWG v${{ env.GL_VERSION }} (AXT1800)"
          tag_name: "${{ github.ref_name }}"
          files: openwrt-src/awg/*.ipk
