name: Build AmneziaWG for AXT1800 Slate (SDK)

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:

permissions:
  contents: write

env:
  SDK_TARGET: ipq807x-2102   # AXT1800/AX1800 v4.x+
  GL_VERSION: '4.8.0'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1) Checkout your fork (contains config_4.8.0.buildinfo + amneziawg-* dirs)
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Clone the GL.iNet SDK repo
      - name: Checkout GL.iNet SDK
        uses: actions/checkout@v4
        with:
          repository: gl-inet/sdk
          path: glinet-sdk

      # 3) Download the AXT1800 SDK into glinet-sdk/<target>/
      - name: Download AXT1800 SDK
        run: |
          cd glinet-sdk
          chmod +x download.sh
          ./download.sh ${{ env.SDK_TARGET }}

      # 4) Copy in your full .config (the buildinfo you generated)
      - name: Apply GL.iNet buildinfo (.config)
        run: |
          cp config_${{ env.GL_VERSION }}.buildinfo \
             glinet-sdk/${{ env.SDK_TARGET }}/.config

      # 5) Overlay your three AmneziaWG packages into the SDK
      - name: Overlay AmneziaWG packages
        run: |
          PKGS="amneziawg-tools luci-proto-amneziawg kmod-amneziawg"
          for pkg in $PKGS; do
            cp -r $pkg glinet-sdk/${{ env.SDK_TARGET }}/package/
          done

      # 6) Build just your three packages
      - name: Build AmneziaWG packages
        run: |
          cd glinet-sdk/${{ env.SDK_TARGET }}
          make package/amneziawg-tools/compile   V=s -j"$(nproc)"
          make package/luci-proto-amneziawg/compile V=s -j"$(nproc)"
          make package/kmod-amneziawg/compile     V=s -j"$(nproc)"

      # 7) Gather the resulting .ipk files
      - name: Collect artifacts
        run: |
          cd glinet-sdk/${{ env.SDK_TARGET }}
          mkdir -p awg
          cp bin/packages/arm_cortex-a15+neon-vfpv4_musl_eabi/base/amneziawg-tools_*.ipk awg/
          cp bin/packages/arm_cortex-a15+neon-vfpv4_musl_eabi/base/luci-proto-amneziawg_*.ipk awg/
          cp bin/targets/ipq807x/generic/packages/kmod-amneziawg_*.ipk        awg/

      # 8) Publish them as a GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name:    "AmneziaWG v${{ env.GL_VERSION }} (AXT1800 SDK)"
          tag_name: "${{ github.ref_name }}"
          files:   glinet-sdk/${{ env.SDK_TARGET }}/awg/*.ipk
