name: Build AmneziaWG for AXT1800 Slate (SDK)

on:
  push:
    tags: ['v*.*.*']
  workflow_dispatch:

permissions:
  contents: write

env:
  SDK_REPO: https://github.com/gl-inet/sdk.git
  SDK_TARGET: ipq_ipq60xx-qsdk11     # the AXT1800 “ipq_ipq60xx” target in GL.iNet’s naming
  GL_VERSION: '4.8.0'                # for naming your release

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1️⃣ Checkout **your** fork, with overlay + config_4.8.0.buildinfo
      - name: Checkout overlay
        uses: actions/checkout@v4

      # 2️⃣ Grab the GL.iNet SDK
      - name: Clone GL.iNet SDK repo
        run: |
          git clone --depth 1 "${{ env.SDK_REPO }}" glinet-sdk

      # 3️⃣ Download the prebuilt SDK for AXT1800
      - name: Download AXT1800 SDK
        run: |
          cd glinet-sdk
          chmod +x download.sh
          ./download.sh "${{ env.SDK_TARGET }}"

      # 4️⃣ Copy your three AmneziaWG dirs into the SDK
      - name: Overlay AmneziaWG packages
        run: |
          cd glinet-sdk/sdk/${{ env.SDK_TARGET }}
          # create the package folder if it doesn’t already exist
          mkdir -p package
          cp -r $GITHUB_WORKSPACE/amneziawg-tools     package/
          cp -r $GITHUB_WORKSPACE/luci-proto-amneziawg feeds/luci/
          cp -r $GITHUB_WORKSPACE/kmod-amneziawg     package/

      # 5️⃣ Copy in your full .config (the GL.iNet buildinfo you generated)
      - name: Apply GL.iNet buildinfo (.config)
        run: |
          cd glinet-sdk/sdk/${{ env.SDK_TARGET }}
          cp $GITHUB_WORKSPACE/config_${{ env.GL_VERSION }}.buildinfo .config

      # 6️⃣ Build **only** your three packages via the SDK’s builder.sh
      - name: Build AmneziaWG packages
        run: |
          cd glinet-sdk/sdk/${{ env.SDK_TARGET }}
          ./builder.sh amneziawg-tools luci-proto-amneziawg kmod-amneziawg

      # 7️⃣ Gather .ipks into one folder
      - name: Collect artifacts
        run: |
          cd glinet-sdk/sdk/${{ env.SDK_TARGET }}/bin/openwrt-sdk
          mkdir -p awg
          cp bin/*/*/amneziawg-tools_*.ipk awg/
          cp bin/*/*/luci-proto-amneziawg_*.ipk awg/
          cp bin/*/*/kmod-amneziawg_*.ipk awg/

      # 8️⃣ Publish a GitHub release with those IPKs
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ github.ref_name }}"
          name: "AmneziaWG v${{ env.GL_VERSION }} (AXT1800)"
          files: glinet-sdk/sdk/${{ env.SDK_TARGET }}/bin/openwrt-sdk/awg/*
