name: Smoke-test AmneziaWG overlay

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout your overlay repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2) Clone OpenWrt 23.05 snapshot
      - name: Clone OpenWrt snapshot
        run: |
          git clone --depth 1 \
            --branch openwrt-23.05 \
            https://github.com/openwrt/openwrt.git openwrt-src

      # 3) Apply your .config (buildinfo renamed to .config)
      - name: Apply .config
        run: |
          cp config_4.8.0.buildinfo openwrt-src/.config

      # 4) Find any dirs with "amneziawg" in their name
      - name: Find local AmneziaWG packages
        run: |
          PKGS=$(find . -maxdepth 1 -type d -name '*amneziawg*' | sed 's#^\./##')
          echo "→ matched packages: $PKGS"
          if [ -z "$PKGS" ]; then
            echo "❌ No AmneziaWG dirs found at repo root!" >&2
            exit 1
          fi

      # 5) Copy them into openwrt-src/package/
      - name: Overlay packages
        run: |
          mkdir -p openwrt-src/package
          cp -rv $PKGS openwrt-src/package/
          echo "→ now under openwrt-src/package:"
          ls openwrt-src/package

      # 6) Verify each overlay folder is present
      - name: Verify overlay
        run: |
          for pkg in amneziawg-tools kmod-amneziawg luci-proto-amneziawg; do
            if [ ! -d openwrt-src/package/$pkg ]; then
              echo "❌ missing openwrt-src/package/$pkg" >&2
              exit 1
            fi
          done
          echo "✅ overlay looks good!"
