name: Smoke-test AmneziaWG overlay

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout your overlay repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2) Clone OpenWrt 23.05 snapshot
      - name: Clone OpenWrt snapshot
        run: |
          git clone --depth 1 \
            --branch openwrt-23.05 \
            https://github.com/openwrt/openwrt.git openwrt-src

      # 3) Apply your GL.iNet buildinfo as .config
      - name: Apply GL.iNet buildinfo (.config)
        run: |
          cp config_4.8.0.buildinfo openwrt-src/.config

      # 4) Find + copy overlay dirs in one go
      - name: Overlay AmneziaWG packages
        run: |
          # enable nullglob so pattern with no matches yields empty array
          shopt -s nullglob
          dirs=( *amneziawg* )
          echo "→ matched overlays: ${dirs[*]}"
          if [ ${#dirs[@]} -eq 0 ]; then
            echo "❌ No overlay directories matching '*amneziawg*' found." >&2
            exit 1
          fi
          mkdir -p openwrt-src/package
          cp -rv "${dirs[@]}" openwrt-src/package/
          echo "→ now under openwrt-src/package/:"
          ls openwrt-src/package

      # 5) Verify each overlay folder is in place
      - name: Verify overlay packages present
        run: |
          for pkg in amneziawg-tools kmod-amneziawg luci-proto-amneziawg; do
            if [ ! -d openwrt-src/package/$pkg ]; then
              echo "❌ Missing overlay package: $pkg" >&2
              exit 1
            fi
          done
          echo "✅ overlay looks good!"
